name: Data Science CI Pipeline

on: [push]  # Runs on every push to the repo

jobs:
  test:
    runs-on: ubuntu-latest  # Uses a Linux machine
    steps:
      - uses: actions/checkout@v4  # Downloads your code
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # You can change this
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run simple test
        run: python main.py
